version: "3.7"
services:
   manage-db:
      image: mysql:5.7
      environment:
          MYSQL_DATABASE: RoomManagement
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_HOST: '%'
      ports:
        - 3306:3306
      command:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
      volumes:
      - /var/lib/mysql
   manage:
      build: .
      ports:
        - 8080:8080
      environment:
         MYSQL_DATABASE_NAME: manage-db
      restart: always
      depends_on:
        - manage-db
      links:
        - manage-db
